version: '3'
services:
  mqtt:
    container_name: eva_farm_mqtt
    image: eclipse-mosquitto
    networks:
      eva_farm_ic:
        ipv4_address: 10.27.12.200

  eva-uc1:
    container_name: eva_farm_uc1
    image: altertech/eva-ics:3.3.2-2021040205-24
    hostname: farm-uc1
    environment:
      - auto_install=1
      - mqtt=10.27.12.200
      - product=uc
      - layout=enterprise
      - MASTERKEY=demo123
      - DEFAULTKEY=demo-default
    networks:
      eva_farm_ic:
        ipv4_address: 10.27.12.101

  eva-uc2:
    container_name: eva_farm_uc2
    image: altertech/eva-ics:3.3.2-2021040205-24
    hostname: farm-uc2
    environment:
      - auto_install=1
      - mqtt=10.27.12.200
      - product=uc
      - layout=enterprise
      - MASTERKEY=demo123
      - DEFAULTKEY=demo-default
    networks:
      eva_farm_ic:
        ipv4_address: 10.27.12.102

  eva-scada:
    container_name: eva_farm_scada
    image: altertech/eva-ics:3.3.2-2021040205-24
    hostname: farm-scada
    ports:
      - "8828:8828"
    environment:
      - auto_install=1
      - mqtt=10.27.12.200
      - link=1
      - product="lm sfa"
      - layout=enterprise
      - MASTERKEY=demo123
      - DEFAULTKEY=demo-default
      - OPPASSWD=123
      - cloud_manager=1
      - after_install=/deploy/deploy.sh
    volumes:
        - ./ui:/ui
        - ./deploy:/deploy
    networks:
      eva_farm_ic:
        ipv4_address: 10.27.12.199

networks:
  eva_farm_ic:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.27.12.0/24

volumes:
  ui:
  cfg:
