version: '3'
services:
  mqtt:
    container_name: eva_farm_mqtt
    image: eclipse-mosquitto:1.6.15
    networks:
      eva_farm_ic:
        ipv4_address: 10.27.12.200

  eva-uc1:
    container_name: eva_farm_uc1
    image: altertech/eva-ics:3.4.0-2021070902-34
    hostname: farm-uc1
    environment:
      - MASTERKEY=demo123
      - DEFAULTKEY=demo-default
    networks:
      eva_farm_ic:
        ipv4_address: 10.27.12.101
    volumes:
      - ./setup/prepare-uc-node.sh:/setup/prepare.sh
      - ./setup/setup-cloud.sh:/setup/setup.sh

  eva-uc2:
    container_name: eva_farm_uc2
    image: altertech/eva-ics:3.4.0-2021070902-34
    hostname: farm-uc2
    environment:
      - MASTERKEY=demo123
      - DEFAULTKEY=demo-default
    networks:
      eva_farm_ic:
        ipv4_address: 10.27.12.102
    volumes:
      - ./setup/prepare-uc-node.sh:/setup/prepare.sh
      - ./setup/setup-cloud.sh:/setup/setup.sh

  eva-scada:
    container_name: eva_farm_scada
    image: altertech/eva-ics:3.4.0-2021070902-34
    hostname: farm-scada
    ports:
      - "8828:8828"
    environment:
      - MASTERKEY=demo123
      - DEFAULTKEY=demo-default
      - after_install=/deploy/deploy.sh
    volumes:
        - ./ui:/ui
        - ./deploy:/deploy
        - ./setup/prepare-scada-node.sh:/setup/prepare.sh
        - ./setup/setup-scada-node.sh:/setup/setup.sh
    networks:
      eva_farm_ic:
        ipv4_address: 10.27.12.199

networks:
  eva_farm_ic:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.27.12.0/24

volumes:
  ui:
  cfg:
